Updated runjob and runscript in test_1 to include option to turn off debug messages, as done by jp in commit cf653c1 to old MoistModel. Also added simple error catching to runjob, so that loop doesn't continue if runscript exits with an error.

diff --git a/exp/test_1/runjob b/exp/test_1/runjob
--- a/exp/test_1/runjob
+++ b/exp/test_1/runjob
@@ -27,6 +27,12 @@ for ((i=0; i < 2; i++))
 	
 do
 	./runscript $i 
+	error_code=$?
+	if [ $error_code != 0 ]; then
+		echo 'error somewhere in runscript'
+		echo $error_code
+		exit
+        fi
 	#mv terminal.log log_files/terminal.log.run$i 
 done
 
